base: &base
  username: vistazo
  password: vistazo
  client_id: 431161751732.apps.googleusercontent.com
  google_secret: ESHRIGC6PHY15jbWwSCG0HcL
  email_service_username:
  email_service_password:
  email_service_domain:
  send_from_email: info@vistazoapp.com
  google_user_name: vistazoapp
  google_password: 5gZ*pBirc
development:
  email_service_domain: localhost
  base_url: http://localhost:6100
  <<: *base
production:
  email_service_domain: heroku.com
  base_url: http://vistazoapp.com
  <<: *base
staging:
  email_service_domain: heroku.com
  base_url: http://vistazo-staging.herokuapp.com
  <<: *base
test:
  email_service_domain: localhost
  base_url: http://vistazo-testing.pebbleit.com
  <<: *base  