base: &base
  username: vistazo
  password: vistazo
  client_id: 443819582294.apps.googleusercontent.com
  google_secret: nBlfJxFwHbyOKN_PKSgTJtbt
development:
  <<: *base
production:
  <<: *base
staging:
  <<: *base
  